# Site settings
title: Francesco Servida
description: Just me and my projects
#baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.francescoservida.ch" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Francesco Servida
user_description: PhD Student in Digital Forensics. MSc in Forensic Sciences, Digital Investigation and Identification, I love programming, sailing, running and doing mad projects in pretty much any field.
user_title: MSc in Forensic Science, Digital Investigation and Identification
#email: anon@anon.com
linkedin_username: servida
twitter_username: fservida
github_username:  fservida
#gplus_username:  lorem_ipsum

blog_url: https://blog.francescoservida.ch
unisciences: https://www.unil.ch/unisciences/francescoservida

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
